import { useEffect, useState } from "react";
import { getDataReport } from "../api/data";

type Item = { source_category?: string; likelihood_score?: number; confidence_score?: number; priority_tier?: string; recommended_inspection?: string };

export function SourceIntelligencePage() {
  const [city, setCity] = useState("delhi-ncr");
  const [items, setItems] = useState<Item[]>([]);
  const [priorities, setPriorities] = useState<Item[]>([]);
  const [error, setError] = useState("");
  useEffect(() => { void Promise.all([getDataReport(`/intelligence/attribution?city=${city}&pollutant=pm2_5`), getDataReport(`/intelligence/priorities?city=${city}`)]).then(([a, b]) => { setItems(((a as { data?: Item[] }).data ?? [])); setPriorities(((b as { data?: Item[] }).data ?? [])); }).catch(() => setError("Historical intelligence outputs could not be loaded.")); }, [city]);
  const ranked = [...items].sort((a, b) => (b.likelihood_score ?? 0) - (a.likelihood_score ?? 0)).slice(0, 7);
  return <section className="mx-auto max-w-7xl px-6 py-16 lg:px-10"><p className="text-xs font-semibold uppercase tracking-[.18em] text-air">Internal decision support</p><h1 className="mt-3 text-4xl font-semibold">Source intelligence</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-mist">Historical, station-centred source influence screening. Scores are evidence-supported likelihood indicators, never confirmed emissions sources, source apportionment, or causal intervention effects.</p><label className="mt-8 block text-sm text-mist">City <select className="ml-3 rounded border border-line bg-panel px-3 py-2 text-white" value={city} onChange={(e) => setCity(e.target.value)}><option value="agra">Agra</option><option value="amritsar">Amritsar</option><option value="delhi-ncr">Delhi NCR</option><option value="lucknow">Lucknow</option><option value="ludhiana">Ludhiana</option></select></label>{error && <p className="mt-4 text-red-300">{error}</p>}<div className="mt-8 grid gap-5 lg:grid-cols-2"><article className="rounded-xl border border-line bg-panel/50 p-5"><h2 className="font-medium">Source-likelihood ranking</h2><div className="mt-5 space-y-4">{ranked.map((x, i) => <div key={`${x.source_category}-${i}`}><div className="flex justify-between text-sm"><span>{x.source_category?.replaceAll("_", " ")}</span><span>{Math.round((x.likelihood_score ?? 0) * 100)}%</span></div><div className="mt-2 h-2 rounded bg-ink"><div className="h-2 rounded bg-air" style={{ width: `${(x.likelihood_score ?? 0) * 100}%` }} /></div><p className="mt-1 text-xs text-mist">Evidence confidence: {Math.round((x.confidence_score ?? 0) * 100)}%</p></div>)}</div></article><article className="rounded-xl border border-line bg-panel/50 p-5"><h2 className="font-medium">Priority and limitations</h2>{priorities.map((x, i) => <div className="mt-4 border-b border-line pb-4 text-sm" key={i}><p className="text-air">{x.priority_tier}</p><p>{x.recommended_inspection}</p></div>)}<p className="mt-5 text-xs leading-6 text-mist">FIRMS time-aligned events, Sentinel-5P valid pixels, GHSL population, and complete OSM source geometry are unavailable or partial. The wind view is a receptor-centred atmospheric indicator; no precise plume map is shown.</p></article></div></section>;
}
