import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ReferenceArea } from "recharts";

import type { DashboardForecast } from "../../api/product";
import { forecastAvailability } from "../../api/product";
import { EmptyState, LimitationNotice, ReadinessBadge } from "./ProductStates";

const value = (number: number | null) => number === null ? "Unavailable" : `${number.toFixed(1)} µg/m³`;
export function ForecastChart({ forecast }: { forecast: DashboardForecast }) {
  const availability = forecastAvailability(forecast);
  const chartData = forecast.points.map((point) => ({ ...point, label: new Date(point.timestamp_utc).toLocaleString([], { month: "short", day: "numeric", hour: "2-digit" }) }));
  if (!forecast.points.length) return <EmptyState message="The replay did not return any forecast trajectory points." />;
  return <section aria-label={`Historical ${forecast.pollutant} forecast chart`}><div className="mb-3 flex flex-wrap gap-2">{Object.entries(availability).map(([name, ready]) => <ReadinessBadge key={name} ready={ready} label={`${name} ${ready ? "available" : "unavailable"}`} />)}</div><div className="h-[340px] w-full min-w-0"><ResponsiveContainer><LineChart data={chartData} margin={{ top: 12, right: 18, bottom: 10, left: 4 }}><CartesianGrid strokeDasharray="3 3" stroke="#29423a" /><XAxis dataKey="label" minTickGap={38} tick={{ fill: "#a9bdb4", fontSize: 11 }} /><YAxis unit={` ${forecast.unit}`} tick={{ fill: "#a9bdb4", fontSize: 11 }} width={72} /><Tooltip contentStyle={{ background: "#10231d", border: "1px solid #29423a" }} /><Legend wrapperStyle={{ fontSize: 12 }} />{availability.uncertainty && <ReferenceArea y1={0} fill="#53d6a2" fillOpacity={0.05} />}{availability.actual && <Line type="linear" dataKey="actual" name="Actual held-out value" stroke="#ffffff" strokeWidth={2} dot={false} connectNulls={false} />}{availability.prediction && <Line type="linear" dataKey="prediction" name="Champion prediction" stroke="#53d6a2" strokeWidth={2} dot={false} connectNulls={false} />}{availability.persistence && <Line type="linear" dataKey="persistence" name="Persistence baseline" stroke="#f6c453" strokeDasharray="6 4" dot={false} connectNulls={false} />}{availability.uncertainty && <><Line type="linear" dataKey="lower" name="Lower interval" stroke="#65aef7" strokeDasharray="3 3" dot={false} connectNulls={false} /><Line type="linear" dataKey="upper" name="Upper interval" stroke="#65aef7" strokeDasharray="3 3" dot={false} connectNulls={false} /></>}</LineChart></ResponsiveContainer></div><p className="sr-only">{forecast.pollutant} replay for {forecast.horizon} hours issued {forecast.issue_timestamp}. Peak champion prediction is {value(Math.max(...forecast.points.flatMap((point) => point.prediction === null ? [] : [point.prediction])))}. Actual series is {availability.actual ? "available" : "unavailable"}; persistence is {availability.persistence ? "available" : "unavailable"}; uncertainty is {availability.uncertainty ? "available" : "unavailable"}.</p></section>;
}
export function ForecastMetricSummary({ forecast }: { forecast: DashboardForecast }) { const availability = forecastAvailability(forecast); return <article className="rounded-xl border border-line bg-panel/50 p-5"><h2 className="font-medium">Replay model and series</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-mist">Model selection</dt><dd>{forecast.model}</dd></div><div><dt className="text-mist">Unit</dt><dd>{forecast.unit}</dd></div><div><dt className="text-mist">Actual series</dt><dd>{availability.actual ? "Available" : "Unavailable"}</dd></div><div><dt className="text-mist">Persistence comparison</dt><dd>{availability.persistence ? "Available" : "Unavailable"}</dd></div></dl><p className="mt-4 text-xs text-mist">Model ID, scope, MAE and RMSE are not supplied by this endpoint, so no metric is inferred.</p><LimitationNotice items={forecast.limitations} /></article>; }
