import type { Pollutant } from "../../api/product";

type SelectProps = { label: string; value: string | number; onChange?: (value: string) => void; options: Array<{ value: string; label: string }>; disabled?: boolean };
function SelectControl({ label, value, onChange, options, disabled }: SelectProps) { return <label className="grid gap-1 text-xs font-medium text-mist">{label}<select className="rounded border border-line bg-panel px-3 py-2 text-sm text-white disabled:cursor-not-allowed disabled:opacity-60" value={value} disabled={disabled} onChange={(event) => onChange?.(event.target.value)}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }
const cities = ["agra", "amritsar", "delhi-ncr", "lucknow", "ludhiana"];
export function CitySelector(props: { value: string; onChange: (value: string) => void }) { return <SelectControl label="Pilot city" value={props.value} onChange={props.onChange} options={cities.map((city) => ({ value: city, label: city === "delhi-ncr" ? "Delhi NCR" : city[0].toUpperCase() + city.slice(1) }))} />; }
export function StationSelector({ stationId }: { stationId?: string }) { return <SelectControl label="Station" value={stationId ?? "Loading station"} disabled options={[{ value: stationId ?? "Loading station", label: stationId ?? "Loading station" }]} />; }
export function PollutantSelector(props: { value: Pollutant; onChange: (value: Pollutant) => void }) { return <SelectControl label="Pollutant" value={props.value} onChange={(value) => props.onChange(value as Pollutant)} options={[{ value: "pm2_5", label: "PM2.5" }, { value: "pm10", label: "PM10" }]} />; }
export function HorizonSelector(props: { value: number; onChange: (value: 24 | 48 | 72) => void }) { return <SelectControl label="Replay horizon" value={props.value} onChange={(value) => props.onChange(Number(value) as 24 | 48 | 72)} options={[24, 48, 72].map((value) => ({ value: String(value), label: `${value} hours` }))} />; }
export function ReplayTimestampSelector({ timestamp }: { timestamp?: string }) { return <SelectControl label="Replay issue timestamp" value={timestamp ?? "Issued by replay"} disabled options={[{ value: timestamp ?? "Issued by replay", label: timestamp ? new Date(timestamp).toLocaleString() : "Issued by replay" }]} />; }
export function LanguageSelector(props: { value: string; onChange: (value: string) => void }) { return <SelectControl label="Language" value={props.value} onChange={props.onChange} options={[{ value: "en", label: "English" }, { value: "hi", label: "हिन्दी" }, { value: "pa", label: "ਪੰਜਾਬੀ" }]} />; }
export function AudienceSelector({ value = "general_public", onChange }: { value?: string; onChange?: (value: string) => void }) { return <SelectControl label="Audience" value={value} onChange={onChange} options={[{ value: "general_public", label: "General public" }]} />; }
export function AdvisoryFormatSelector({ value = "standard", onChange }: { value?: string; onChange?: (value: string) => void }) { return <SelectControl label="Format" value={value} onChange={onChange} options={[{ value: "short", label: "Short" }, { value: "standard", label: "Standard" }, { value: "detailed", label: "Detailed" }]} />; }
export function ScenarioStrengthSelector() { return <SelectControl label="Scenario strength" value="reported" disabled options={[{ value: "reported", label: "Reported sensitivity" }]} />; }
